ALTER TABLE player ADD COLUMN IF NOT EXISTS current_skill_level VARCHAR(20);

ALTER TABLE player ADD CONSTRAINT IF NOT EXISTS chk_player_current_skill_level
    CHECK (current_skill_level IS NULL OR current_skill_level IN ('DEBUTANT', 'ADVANCED', 'SKILLED'));

CREATE TABLE IF NOT EXISTS player_skill_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    player_id BIGINT NOT NULL,
    skill_level VARCHAR(20) NOT NULL CHECK (skill_level IN ('DEBUTANT', 'ADVANCED', 'SKILLED')),
    changed_at TIMESTAMP NOT NULL,
    changed_by_admin_id BIGINT,
    evaluation_event_id BIGINT,
    description VARCHAR(255),
    CONSTRAINT fk_player_skill_history_player FOREIGN KEY (player_id) REFERENCES player(id),
    CONSTRAINT fk_player_skill_history_admin FOREIGN KEY (changed_by_admin_id) REFERENCES admin(id),
    CONSTRAINT fk_player_skill_history_event FOREIGN KEY (evaluation_event_id) REFERENCES evaluation_event(id)
);

CREATE INDEX IF NOT EXISTS idx_player_skill_history_player_changed
    ON player_skill_history(player_id, changed_at DESC);
