CREATE TABLE field (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    location VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    team_id BIGINT NOT NULL,
    field_id BIGINT NOT NULL,
    date_time TIMESTAMP NOT NULL,
    duration_minutes INTEGER NOT NULL,
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    notes VARCHAR(500),
    cancel_reason VARCHAR(500),
    CONSTRAINT fk_schedule_team FOREIGN KEY (team_id) REFERENCES team(id),
    CONSTRAINT fk_schedule_field FOREIGN KEY (field_id) REFERENCES field(id),
    CONSTRAINT ck_schedule_duration CHECK (duration_minutes IN (60, 90, 120)),
    CONSTRAINT ck_schedule_type CHECK (type IN ('TRAINING', 'MATCH', 'OTHER')),
    CONSTRAINT ck_schedule_status CHECK (status IN ('SCHEDULED', 'CANCELED'))
);

INSERT INTO field (uuid, name, location, active)
VALUES
    (RANDOM_UUID(), 'Main Field', 'Club facilities', TRUE),
    (RANDOM_UUID(), 'Training Field', 'Club facilities', TRUE);
