CREATE TABLE championship (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    team_id BIGINT NOT NULL,
    start_month INTEGER NOT NULL,
    start_year INTEGER NOT NULL,
    end_month INTEGER NOT NULL,
    end_year INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_championship_team FOREIGN KEY (team_id) REFERENCES team(id),
    CONSTRAINT ck_championship_start_month CHECK (start_month BETWEEN 1 AND 12),
    CONSTRAINT ck_championship_end_month CHECK (end_month BETWEEN 1 AND 12)
);

CREATE TABLE championship_roster (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    championship_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    trainer_id BIGINT NOT NULL,
    assigned_date DATE NOT NULL,
    removed_date DATE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_championship_roster_championship FOREIGN KEY (championship_id) REFERENCES championship(id),
    CONSTRAINT fk_championship_roster_player FOREIGN KEY (player_id) REFERENCES player(id),
    CONSTRAINT fk_championship_roster_trainer FOREIGN KEY (trainer_id) REFERENCES trainer(id)
);
