INSERT INTO club_setup (uuid, type, json_data)
VALUES (
    RANDOM_UUID(),
    'MATCH_IMPROVEMENT_OPPORTUNITY',
    '["Improve pass", "Improve physical preparation", "Improve shooting", "Improve positioning", "Improve decision making", "Excessive ball control"]'
);

INSERT INTO club_setup (uuid, type, json_data)
VALUES (
    RANDOM_UUID(),
    'MATCH_HIGHLIGHT',
    '["Goal scored", "Goals scored", "Assist made", "Good shots", "Good passes", "Tackles and interceptions", "Good physical condition"]'
);

CREATE TABLE team_match (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    team_id BIGINT NOT NULL,
    championship_id BIGINT,
    opponent VARCHAR(120) NOT NULL,
    place VARCHAR(120) NOT NULL,
    match_date_time TIMESTAMP NOT NULL,
    team_score INTEGER,
    opponent_score INTEGER,
    notes VARCHAR(500),
    CONSTRAINT fk_team_match_team FOREIGN KEY (team_id) REFERENCES team(id),
    CONSTRAINT fk_team_match_championship FOREIGN KEY (championship_id) REFERENCES championship(id),
    CONSTRAINT ck_team_match_team_score CHECK (team_score IS NULL OR team_score >= 0),
    CONSTRAINT ck_team_match_opponent_score CHECK (opponent_score IS NULL OR opponent_score >= 0)
);

CREATE TABLE match_player_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    match_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    improvement_tags TEXT NOT NULL,
    highlight_tags TEXT NOT NULL,
    notes VARCHAR(1000),
    CONSTRAINT fk_match_player_analysis_match FOREIGN KEY (match_id) REFERENCES team_match(id),
    CONSTRAINT fk_match_player_analysis_player FOREIGN KEY (player_id) REFERENCES player(id),
    CONSTRAINT uk_match_player_analysis_match_player UNIQUE (match_id, player_id)
);
