CREATE TABLE IF NOT EXISTS audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    occurred_at TIMESTAMP NOT NULL,
    actor_admin_id BIGINT,
    actor_name VARCHAR(100),
    action VARCHAR(40) NOT NULL,
    entity_type VARCHAR(60) NOT NULL,
    entity_uuid UUID NOT NULL,
    entity_label VARCHAR(255),
    message VARCHAR(500),
    CONSTRAINT fk_audit_event_actor_admin FOREIGN KEY (actor_admin_id) REFERENCES admin(id)
);

CREATE INDEX IF NOT EXISTS idx_audit_event_occurred_at
    ON audit_event(occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_event_entity
    ON audit_event(entity_type, entity_uuid);

CREATE INDEX IF NOT EXISTS idx_audit_event_action
    ON audit_event(action);

CREATE INDEX IF NOT EXISTS idx_audit_event_actor_admin
    ON audit_event(actor_admin_id);
