CREATE TABLE club_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    analysis_date DATE NOT NULL UNIQUE,
    generated_at TIMESTAMP NOT NULL
);

CREATE TABLE club_analysis_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    analysis_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    title VARCHAR(150) NOT NULL,
    message VARCHAR(500) NOT NULL,
    affected_records TEXT NOT NULL,
    CONSTRAINT fk_club_analysis_item_analysis FOREIGN KEY (analysis_id) REFERENCES club_analysis(id)
);

CREATE INDEX idx_club_analysis_generated_at
    ON club_analysis(generated_at DESC);

CREATE INDEX idx_club_analysis_item_analysis
    ON club_analysis_item(analysis_id);
