CREATE TABLE team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    age_group VARCHAR(50) NOT NULL,
    team_category VARCHAR(20) NOT NULL CHECK (team_category IN ('MASCULINE', 'FEMININE')),
    trainer_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_team_trainer FOREIGN KEY (trainer_id) REFERENCES trainer(id)
);

