CREATE TABLE player_team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    player_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    assigned_date DATE NOT NULL,
    removed_date DATE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_player_team_player FOREIGN KEY (player_id) REFERENCES player(id),
    CONSTRAINT fk_player_team_team FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE INDEX idx_player_team_team_active ON player_team(team_id, active);
CREATE INDEX idx_player_team_player_active ON player_team(player_id, active);

